name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt

      - name: Install wasm-pack
        run: cargo install wasm-pack

      - name: Build WASM package
        run: wasm-pack build --target bundler

  semgrep:
    runs-on: ubuntu-latest
    if: github.actor != 'kitabisaengineer' && !endsWith(github.actor, '[bot]')
    container:
      image: semgrep/semgrep
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Semgrep
        run: semgrep scan --config auto
